import { Code, Server, Database, Brain, Smartphone, Globe, GitBranch, Layers, Users } from "lucide-react";

export const PLANETS = [
  {
    name: "Mercury",
    skill: "HTML/CSS",
    description: "Frontend Foundation",
    color: "hsl(0, 0%, 60%)",
    size: 24,
    orbitRadius: 70,
    orbitDuration: 8,
    icon: () => <Code className="w-3 h-3" />,
    hasRings: false,
  },
  {
    name: "Venus",
    skill: "JavaScript",
    description: "Dynamic Programming",
    color: "hsl(45, 100%, 60%)",
    size: 28,
    orbitRadius: 90,
    orbitDuration: 12,
    icon: () => <span className="text-xs font-bold">JS</span>,
    hasRings: false,
  },
  {
    name: "Earth",
    skill: "React.js",
    description: "Frontend Framework",
    color: "hsl(220, 100%, 50%)",
    size: 32,
    orbitRadius: 110,
    orbitDuration: 16,
    icon: () => <span className="text-xs font-bold">⚛️</span>,
    hasRings: false,
  },
  {
    name: "Mars",
    skill: "Node.js",
    description: "Backend Runtime",
    color: "hsl(15, 100%, 50%)",
    size: 28,
    orbitRadius: 130,
    orbitDuration: 24,
    icon: () => <Server className="w-3 h-3" />,
    hasRings: false,
  },
  {
    name: "Jupiter",
    skill: "Python",
    description: "Programming Language",
    color: "hsl(30, 60%, 45%)",
    size: 48,
    orbitRadius: 160,
    orbitDuration: 32,
    icon: () => <span className="text-sm font-bold">🐍</span>,
    hasRings: false,
  },
  {
    name: "Saturn",
    skill: "Data Structures & Algorithms",
    description: "Problem Solving",
    color: "hsl(270, 60%, 60%)",
    size: 40,
    orbitRadius: 190,
    orbitDuration: 48,
    icon: () => <Brain className="w-4 h-4" />,
    hasRings: true,
  },
  {
    name: "Uranus",
    skill: "MongoDB",
    description: "NoSQL Database",
    color: "hsl(180, 60%, 60%)",
    size: 32,
    orbitRadius: 220,
    orbitDuration: 64,
    icon: () => <Database className="w-3 h-3" />,
    hasRings: false,
  },
  {
    name: "Neptune",
    skill: "Express.js",
    description: "Backend Framework",
    color: "hsl(240, 100%, 30%)",
    size: 32,
    orbitRadius: 250,
    orbitDuration: 80,
    icon: () => <Layers className="w-3 h-3" />,
    hasRings: false,
  },
  {
    name: "Pluto",
    skill: "Git",
    description: "Version Control",
    color: "hsl(0, 0%, 70%)",
    size: 24,
    orbitRadius: 280,
    orbitDuration: 96,
    icon: () => <GitBranch className="w-3 h-3" />,
    hasRings: false,
  },
];